filebeat.inputs:
- type: docker
  containers.ids:
    - "*"
processors:
   
- add_docker_metadata: ~
   
- drop_event:
   
    when:
   
      not:
   
        or:
   
          - equals:
              container.name: "ad-service"

          - equals:
              container.name: "rateboard-currency-handler"
              
          - equals:
              container.name: "rateboard-user-management-service-dev"
   
          - equals:
              container.name: "rateboard-branch-service-dev"
                        
output.elasticsearch:
  hosts: ["http://elk.inside10d.com/"]
  username: "elastic"
  password: "ElastIcadMin"
  indices:
    - index: "rateboard-dev-%{+yyyy.MM.dd}"
  setup.template.name: "rateboard-dev"
  setup.template.pattern: "rateboard-dev-*"