# apigateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: servicetypes-service
spec:
  selector:
    app: servicetypes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: systementry-service
spec:
  selector:
    app: systementry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
  type: NodePort

